### ISSUE TITLE
Migration Documentation Request - Upgrading MySQL tables to utf8mb4 may be required

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#189]
#### Issue description

During the migration of a non-ISLE Islandora Drupal site, I checked the Status Report (https://domain/admin/reports/status) page and saw the following:

![screen shot 2018-10-26 at 10 20 37](https://user-images.githubusercontent.com/501554/47575578-6a3eba00-d910-11e8-9c56-9fc78b272cd1.png)

There is currently no documentation for potential ISLE users to follow for upgrading their table to utf8mb4. 

Possible solution that requires more testing:

I followed the steps outlined here: https://www.drupal.org/project/utf8mb4_convert

* Shell into your running Apache container: `docker exec -it isle-apache-ld bash` (_example_)
* `cd /var/www/html/`
* `drush @none dl utf8mb4_convert-7.x`
* `drush cc drush`
* Put your site into maintenance mode: `drush vset maintenance_mode 1` (_if needed_)
* `drush utf8mb4-convert-databases` (_This will take 5 -10 mins depending_)
* `drush cc all` (_for good measure_)
* `drush vset maintenance_mode 0` (takes site out of maintenance mode)

 

Additional reading here: https://www.drupal.org/node/2754539

**Comment by g7morris** [comment]
@br2490 Any thoughts on this? Perhaps include in the migration script?

**Comment by br2490** [comment]
@g7morris I think it would be a good candidate for the migration script and also some documentation.  When I migrated Barnard College I had the same error and used the [Drupal module](https://www.drupal.org/project/utf8mb4_convert) that purported to do this upgrade for you without running into issue!

So I think yes, both of those things need to happen.  We just haven't payed a single lick of attention to the migration script because it's not as straight forward and I'm thinking we might need to chunk "them" into bits that make sense; in this e.g.: this is it's own migration shell script just for downloading, enabling, and running the Drupal module for migrators. 

Thoughts all @Islandora-Collaboration-Group/isle-maintainers-commiters-contributors

**Comment by br2490** [comment]
@br2490 @shauntru - tagging us both, let me know if you want to take this on Slack, Shaun.
Create a shell script that is similar in vein to others that performs the following:

``` 
cd /var/www/html/ || exit;
drush @none dl utf8mb4_convert-7.x
drush cc drush
drush vset maintenance_mode 1
drush utf8mb4-convert-databases
drush cc all
drush vset maintenance_mode 0
```
Create this in the https://github.com/Islandora-Collaboration-Group/ISLE-Drupal-Build-Tools repo so it is pulled in on image start.

On next ISLE-Apache rebuild add an `ln -s` for the script in /usr/bin

**Comment by shauntru** [comment]
@br2490 I can take a crack at this script, but I don't know how I would test it. Happy to take up the conversation on Slack to keep the Issue comments clear.

**Comment by g7morris** [comment]
This should become part of the scripts directory. Assigning this to myself for next ISLE release.
