### ISSUE TITLE
Check files under /docs/specifications/ for updates

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#235]
These haven't been touched since the Hack/Doc.  I've removed them from the nav for now as they're all likely out of date.

**Comment by dwk2** [comment]
These files (ISLE\docs\specifications) continue to be out of date, all but one are not publicly displayed (the one live doc is "/specifications/resource-matrix/"), and they all appear to contain historically useful information for understanding how ISLE images are built. I'm unsure if these 6 files should quietly remain in the docs, be assigned for updating (@g7morris ?) or be purged. Thoughts anyone?

diagram-network.md
docker-containers-images.md
dockerfiles.md
resource-matrix.md
supported-drupal-modules-matrix.md
supported-software-matrix.md

**Comment by g7morris** [comment]
Hi @dwk2 

* `diagram-network.md` - Yes this needs an update. I can tweak this slide with minor revisions. 
* `docker-containers-images.md` - Needs some editing and cutting down. Perhaps instead I can just give links to the isle image READMEs and a note/link to the release notes section? 
  * I'd like to reduce the number of areas we all have to update for each release. Seems unnecessarily redundant.
  *  Better we teach peeps about where to look vs actual version numbers. 
* `dockerfiles.md` - Slight amount of editing needed. I can update as needed with ISLE maintainer information as well. Two birds one stone. 
* `resource-matrix` - Seems fine to me. No edits suggested
* `supported-drupal-modules-matrix.md` 
  * This one is tricky and a bit overdone in retrospect.
  * I think we should point out what is "used" but drop the word "supported" in the ISLE demo. 
  * We should just have a link to latest Drupal 7 Core (_not using the version number, we need to stop doing this to ourselves_ )
  * change the file name to `demo-drupal-modules-list.md`
  * Give links to the used Islandora modules without versions
  * Change wording of "test site `isle.localdomain` to "demo site isle-demo.localdomain` Hmm is that a thought too to change isle.localdomain to isle-demo.localdomain? (Much clearer what environment we are using?"
  * Instead of a value in the Version column, just create a link to the Git repo for latest version
  * `supported-software-matrix` is just `docker-containers-images.md` lets ax this file.

**Comment by g7morris** [comment]
Closing as "fixed" from ISLE 1.5.5 release
