### ISSUE TITLE
Stop race condition

### ISSUE THREAD

**Issue by br2490** [Islandora-Collaboration-Group/ISLE#79]
Docker has a few suggests, but I like WAIT FOR IT... wait-for-it.sh

https://github.com/vishnubob/wait-for-it

Could that before fedora to wait for mysql defeat race?

tagging @g7morris

**Comment by br2490** [comment]
tagging @Islandora-Collaboration-Group/isle-steering-committee

**Comment by br2490** [comment]
@g7morris  https://docs.docker.com/compose/startup-order/  the example may be applicable to isle-mysql container - just throwing examples out. 
tagging @Islandora-Collaboration-Group/isle-steering-committee

**Comment by br2490** [comment]
Race condition no longer applies as the docker-compose file can be sequenced properly.  Additionally the immutable sql box means a generic pull and run results in the default isle-required databases and data.  Can you confirm @g7morris and if so, maybe we can deprecate this ticket in favor of one that just explore the docker-compose?

**Comment by br2490** [comment]
see also #106 for healthchecks and controlling start order (or maybe better said controlling start order based on service availability?)

**Comment by g7morris** [comment]
Closing ticket as this race condition is no longer prevalent when running `docker-compose up -d`. The issue has been fixed in the Service areas of the docker-compose.yml file by indicating (example) 

```
    depends_on:
      - mysql
      - solr
```

This allows the containers appropriate time to check or wait for the involved containers to startup PRIOR to executing further commands. Closing ticket.
